### ISSUE TITLE
Smart contract verifier is giving error while compiling

### ISSUE THREAD

**Issue by iqbalsingh108** [blockscout/blockscout-rs#218] opened 2022-11-23 15:38 UTC
Please help me on this issue
![image](https://user-images.githubusercontent.com/4157381/203587334-18145f45-75a1-4a57-b91f-64c7b7abf910.png)

**Comment by rimrakhimov** [comment] 2022-11-23 20:31
@iqbalsingh108 Could you please describe the context what you are doing and what version of compiler you are trying to compile the project

**Comment by leviska** [comment] 2022-11-24 07:21
Can you please checkout latest main branch and reset your working tree to it

**Comment by iqbalsingh108** [comment] 2022-11-27 12:30
![image](https://user-images.githubusercontent.com/4157381/204135226-0d48355e-f699-4238-a0c5-24b263fe5488.png)
New issue

**Comment by rimrakhimov** [comment] 2022-11-28 21:43
@iqbalsingh108 I believe the issue was related to the old version of `protoc`, the requirement that has been added in https://github.com/blockscout/blockscout-rs/commit/b0f36deac53937f5b28fb90b356d1fb28ebdf610 with addition of `sig_provider_extension` dependency.

Since that, we've updated verifier and made that dependency optional in https://github.com/blockscout/blockscout-rs/commit/7b403b80f4cc499b6aa08f5f35ac5c3d7861f983. Could you please try again and see whether the https://github.com/blockscout/blockscout-rs/issues/218#issuecomment-1328236853 problem has been fixed?

Regarding the original question, could you please elaborate more on your setup and actions, so that we can reproduce the problem?

**Comment by 0f0crypto** [comment] 2022-12-30 16:22
I get the same/similar error trying to do a manual deployment using the steps as described [here](https://docs.blockscout.com/for-developers/manual-deployment)

I just tried to install the verification microservice via cargo:

```
cargo install --git https://github.com/blockscout/blockscout-rs smart-contract-verifier-http
```

and I got this error

![image](https://user-images.githubusercontent.com/79452698/210091246-de0b11d8-1135-4bcd-863f-e51ed9f41050.png)

**Comment by ekawibisono** [comment] 2023-01-01 04:02
Can you mention the Cargo or Rustc version?

Maybe you can try installing this

> sudo apt install pkg-config

**Comment by 0f0crypto** [comment] 2023-01-01 11:49
I have the same cargo and rustc versions. 

```bash
cargo --version
cargo 1.66.0 (d65d197ad 2022-11-15)
rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12)
```

The pkg-config is already the latest

```bash
sudo apt install pkg-config
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
pkg-config is already the newest version (0.29.2-1ubuntu3).
```

I've installed everything via `apt-get` on a brand new instance of `jammy`

```bash
sudo apt-get update
sudo apt-get install -y erlang elixir inotify-tools gcc g++ make libtool automake libgmp-dev \
  cargo build-essential postgresql postgresql-contrib node-js
```

and `Rust`

```bash
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
```

Here are some other details

```bash
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy
elixir --version
Erlang/OTP 24 [erts-12.2.1] [source] [64-bit] [smp:3:3] [ds:3:3:10] [async-threads:1] [jit]
Elixir 1.12.2 (compiled with Erlang/OTP 24
node --version
v16.19.0
```

It seems to me that there is actually an issue in the code at `all_metadata_extracting_verifier.rs:189:13` with an incorrect parameter type in the constructor call.

**Comment by ekawibisono** [comment] 2023-01-01 17:20
Maybe you have to start over from the beginning again, try to clone the blockscout-rs again. and then try to install. 

this is my .tool-version blockscout
> elixir 1.13.4-otp-24
> erlang 24.3.4.1
> nodejs 16.16.0

**Comment by rimrakhimov** [comment] 2023-01-02 01:01
@0f0crypto I've updated some dependencies in https://github.com/blockscout/blockscout-rs/pull/286. Could you please try again?

**Comment by 0f0crypto** [comment] 2023-01-02 01:43
@rimrakhimov yeah, it works now for me without any changes (just re-run the command). Thank you!

**Comment by rimrakhimov** [comment] 2023-01-02 10:43
@ekawibisono Thank you for your replies! It helped a lot to make the setup clear
You've also mentioned that you had similar problems with using cargo or rustc beta versions. It would be nice to see whether the problem was fixed for that case as well. If it did, I think I can close the issue

**Closed** 2023-01-09 11:23 UTC
