### ISSUE TITLE
What database does STATS__BLOCKSCOUT_DB_URL refer to?

### ISSUE THREAD

**Issue by XO39** [blockscout/blockscout-rs#859] opened 2024-05-03 01:19 UTC
We are trying to run the microservices directly without a docker as we can't use docker for some reason.
We are are confused about the database that the STATS__BLOCKSCOUT_DB_URL env variable refers to.

Is it the same database that the DATABASE_URL refers to? Or it is a completely different database?

**Comment by bragov4ik** [comment] 2024-05-08 12:46
It is a URL of database for some running blockscout instance, because `stats` service relies on data produced by the explorer.  You'll likely need to run your own instance of blockscout.

FYI you can read descriptions for envs in [readme](https://github.com/blockscout/blockscout-rs/tree/main/stats#env). Soon the docs might be reorganized, but you can refer to that page for now.

Also, you can refer to the dockerfile/docker compose file for configuration example.

**Comment by bragov4ik** [comment] 2024-05-08 12:46
I'll close this since it's not a bug but a question

**Closed by bragov4ik** 2024-05-08 12:46 UTC
