### ISSUE TITLE
cargo compile error

### ISSUE THREAD

**Issue by erdus** [blockscout/blockscout-rs#442] opened 2023-04-24 02:01 UTC
error: failed to run custom build command for `smart-contract-verifier-proto v0.1.0 (/root/.cargo/git/checkouts/blockscout-rs-1329d74b8bb8dea8/745db1d/smart-contract-verifier/smart-contract-verifier-proto)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install4q6wSd/release/build/smart-contract-verifier-proto-b61b14efb720e432/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: v2/smart-contract-verifier.proto:52:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:56:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:89:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:92:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:99:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:113:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:124:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:126:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:131:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nv2/smart-contract-verifier.proto:172:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `smart-contract-verifier-server v0.1.0 (https://github.com/blockscout/blockscout-rs#745db1d0)`, intermediate artifacts can be found at `/tmp/cargo-install4q6wSd`

**Comment by rimrakhimov** [comment] 2023-04-24 08:53
Hi, @erdus. To build the verification service manually you have to update the protobuf version to be at least [3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) where the optional fields has been added to be default. You can check you current

**Comment by erdus** [comment] 2023-04-25 09:13
Thanks.

**Comment by free1** [comment] 2023-04-25 09:41
i got same error

```
protoc --version
libprotoc 3.3.2
```

**Comment by rimrakhimov** [comment] 2023-04-25 11:32
@free1 To build the verification service manually you have to update the protobuf version to be at least [3.15.0](https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0) where the optional fields has been added to be default.

**Comment by rimrakhimov** [comment] 2023-06-04 21:16
@free1 Could you please specify if the problem has been solved and can close the issue?

**Comment by ganzr** [comment] 2023-10-17 07:26
my protoc version is 3.21.4 and i have the same issue. 

error: failed to run custom build command for `smart-contract-verifier-proto v0.1.0 (/root/.cargo/git/checkouts/blockscout-rs-1329d74b8bb8dea8/e261ddf/smart-contract-verifier/smart-contract-verifier-proto)`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installKigl3R/release/build/smart-contract-verifier-proto-1a4dc030edb59349/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=proto/

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: protoc-gen-openapiv2: program not found or is not executable\nPlease specify a program using absolute path or make sure the program is available in your PATH system variable\n--openapiv2_out: protoc-gen-openapiv2: Plugin failed with status code 1.\n" }
warning: build failed, waiting for other jobs to finish...
error: failed to compile `smart-contract-verifier-server v0.1.0 (https://github.com/blockscout/blockscout-rs#e261ddf2)`, intermediate artifacts can be found at `/tmp/cargo-installKigl3R`

**Comment by bragov4ik** [comment] 2024-09-02 15:03
@ganzr as the message says, you also need `protoc-gen-openapiv2` (probably version `v2.19.0` at the time of writing this response) to build the crate

**Closed by bragov4ik** 2024-09-02 15:03 UTC
